.TH prometheus-puppetdb 1 "27 April 2017"
.SH NAME
prometheus-puppetdb \- Prometheus scrape lists based on PuppetDB
.SH SYNOPSIS
\fBprometheus-puppetdb\fP [OPTIONS]
.SH DESCRIPTION

.SH OPTIONS
.SS Application Options
.TP
\fB\fB\-V\fR, \fB\-\-version\fR\fP
Display version.
.TP
\fB\fB\-u\fR, \fB\-\-puppetdb-url\fR <default: \fI"http://puppetdb:8080"\fR>\fP
PuppetDB base URL.
.TP
\fB\fB\-q\fR, \fB\-\-puppetdb-query\fR <default: \fI"inventory[certname, facts] { nodes { deactivated is null } }"\fR>\fP
PuppetDB query.
.TP
\fB\fB\-p\fR, \fB\-\-collectd-port\fR <default: \fI"9103"\fR>\fP
Collectd port.
.TP
\fB\fB\-c\fR, \fB\-\-config-file\fR <default: \fI"/etc/prometheus-targets/prometheus-targets.yml"\fR>\fP
Prometheus target file.
.TP
\fB\fB\-s\fR, \fB\-\-sleep\fR <default: \fI"15s"\fR>\fP
Sleep time between queries.
.TP
\fB\fB\-m\fR, \fB\-\-manpage\fR\fP
Output manpage.
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
