.TH prometheus-puppetdb 1 "19 January 2018"
.SH NAME
prometheus-puppetdb \- Prometheus service discovery based on PuppetDB
.SH SYNOPSIS
\fBprometheus-puppetdb\fP [OPTIONS]
.SH DESCRIPTION

.SH OPTIONS
.SS Application Options
.TP
\fB\fB\-V\fR, \fB\-\-version\fR\fP
Display version.
.TP
\fB\fB\-u\fR, \fB\-\-puppetdb-url\fR <default: \fI"http://puppetdb:8080"\fR>\fP
PuppetDB base URL.
.TP
\fB\fB\-x\fR, \fB\-\-cert-file\fR <default: \fI"certs/client.pem"\fR>\fP
A PEM encoded certificate file.
.TP
\fB\fB\-y\fR, \fB\-\-key-file\fR <default: \fI"certs/client.key"\fR>\fP
A PEM encoded private key file.
.TP
\fB\fB\-z\fR, \fB\-\-cacert-file\fR <default: \fI"certs/cacert.pem"\fR>\fP
A PEM encoded CA's certificate file.
.TP
\fB\fB\-k\fR, \fB\-\-ssl-skip-verify\fR <default: \fI$PROMETHEUS_SSL_SKIP_VERIFY\fR>\fP
Skip SSL verification.
.TP
\fB\fB\-q\fR, \fB\-\-puppetdb-query\fR <default: \fI"facts[certname, value]"\fR>\fP
PuppetDB query.
.TP
\fB\fB\-f\fR, \fB\-\-puppetdb-filter\fR <default: \fI"name='ipaddress' and nodes { deactivated is null }"\fR>\fP
PuppetDB filter.
.TP
\fB\fB\-r\fR, \fB\-\-role-mapping-file\fR <default: \fI"role-mapping.yaml"\fR>\fP
Role mapping configuration file
.TP
\fB\fB\-c\fR, \fB\-\-targets-dir\fR <default: \fI"/etc/prometheus/targets"\fR>\fP
Directory to store File SD targets files.
.TP
\fB\fB\-s\fR, \fB\-\-sleep\fR <default: \fI"60s"\fR>\fP
Sleep time between queries.
.TP
\fB\fB\-m\fR, \fB\-\-manpage\fR\fP
Output manpage.
.SS Help Options
.TP
\fB\fB\-h\fR, \fB\-\-help\fR\fP
Show this help message
