---
version: '3'
services:
  prometheus-server:
    image: prom/prometheus:v2.11.1
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --storage.tsdb.path=/prometheus
      - --web.enable-lifecycle
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-puppetdb-sd-output:/etc/prometheus/puppetdb-sd/puppetdb-sd.yml
  prometheus-puppetdb-sd:
    image: camptocamp/prometheus-puppetdb-sd:0.11.0
    environment:
      OUTPUT_METHOD: file
    volumes:
      - prometheus-puppetdb-sd-output:/etc/prometheus/puppetdb-sd/puppetdb-sd.yml
volumes:
  prometheus-puppetdb-sd-output: {}
