kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "prometheus-puppetdb.fullname" . }}
  labels:
    app: {{ template "prometheus-puppetdb.name" . }}
    chart: {{ template "prometheus-puppetdb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["configmaps"]
  verbs: ["*"]
